### ISSUE TITLE
Merge into alertifyjs/alertify.js

### ISSUE THREAD

**Issue by ChunkRadius** [dbtek/alertify-bootstrap-3#2]
Hey, since the [original alertify.js repo](//github.com/fabien-d/alertify.js] is no longer being maintained, I'm trying to [head up a new fork that's actively maintained](//github.com/alertifyjs/alertify.js). Would you be interested in adding this as a theme and submitting a PR. It looks awesome, and it would be cool to have a built-in Bootstrap 3 theme.

It would be really nice to include it into both the master/0.3 and 0.5 branches. It would make sense to put it in a new `src/css/themes/bootstrap3` or similarly named folder. The build system will automatically add the core css and output it all to a single file.

Thanks!

**Comment by dbtek** [comment]
Hi Brad!
Thanks for stopping by. I would be happy to add the theme to the brand new Alertify fork. I will drop a pr as soon as possible.

**Comment by ChunkRadius** [comment]
Just [merged](https://github.com/alertifyjs/alertify.js/pull/11) it. Thanks so much!
